config/routes.rb
Rails.application.routes.draw do
  # Add your engine routes here
  resources :segments
end

app/models/segment.rb
class Segment < ActiveRecord::Base

  validates_uniqueness_of :key, :scope => :locale
  validates_presence_of :content, :locale
  before_validation :set_default_locale
  
  private
  
  def set_default_locale
    return unless self.locale.nil? || self.locale.blank?
    self.locale = I18n.default_locale
  end
  
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  respond_to(:html, :json, :xml)
  
  layout 'layouts/segment_layout'
  
  #Override authenticate_for_segments to handle authentication
  before_filter :authenticate_for_segments
  before_filter :load_segment, :except => [:index, :new, :create]
  
  def index
    respond_with @segments = Segment.all
  end
  
  def update
    respond_with @segment.update_attributes(params[:segment]), :location => segments_path
  end
  
  def create
    respond_with @segment = Segment.create(params[:segment]), :location => segments_path
  end
  
  def destroy
    respond_with @segment.destroy
  end
  
  def show
    respond_with @segment
  end
  
  
  private
  
  def authenticate_for_segments
    return true
  end
  
  def load_segment
    @segment = Segment.find(params[:id])
  end
end

app/views/layouts/segment_layout.html.erb
<html>
  <head>
    <title><%= t('segments.title') %></title>
    <style type="text/css">
      body { background: #556270; font-size: 16px; font-family: sans-serif;}
      div.container { margin: 20px auto; padding: 20px; border: solid 1px #666; width: 700px; min-height: 500px; background-color: #FCFBE3; }
      label { color: #333; font-size: 80%; font-style: italic; padding: 2px 0; }
      fieldset { border: solid 1px #999; }
      legend { font-weight: bold; }
      form.button_to, form.button_to div { display: inline; }
      a, form.button_to input { margin: 0; padding: 5px; color: #333; text-decoration: none; font-size: 90%; background: none; border: 0; }
      table { width: 100%; border-collapse: collapse; }
      th { text-align: left; }
      td.locale { width: 20%; }
      td.key { width: 50%; }
      td { width: 5%; }
      tr.segment:hover { background-color: #CCC;}
      a:hover, form.button_to input:hover { background-color: #556270; color: #FFF; }
    </style>
  </head>
  
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/segments/_form.html.erb
    <p>
      <%= form.label :locale -%><br />
      <%= form.select :locale, I18n.available_locales -%>
    </p>
   
    <p>
      <%= form.label :key -%><br />
      <%= form.text_field :key -%>
    </p>
    
    <p>
      <%= form.label :content -%><br />
      <%= form.text_area :content, :rows => 5 -%>
    </p>
    
    <p>
      <%= form.submit %>
    </p>

app/views/segments/_segment_row.html.erb
<tr class="segment">
  <td class="locale"><%= segment.locale -%></td>
  <td class="key"><%= segment.key -%></td>
  <td><%= link_to t('segments.show_link'), segment_url(segment) -%></td>
  <td><%= link_to t('segments.edit_link'), edit_segment_url(segment) -%></td>
  <td><%= button_to t('segments.destroy_link'), segment_url(segment), :method => :delete -%></td>
</tr>

app/views/segments/edit.html.erb
<%= content_tag :h1, t('segments.edit.heading', :key => @segment.key, :language => @segment.locale) -%>
<%= form_for @segment do |form| %>
  <%= render :partial => 'form', :locals => {:form => form} -%>
<% end -%>

app/views/segments/index.html.erb
<%= content_tag :h1, t('segments.index.heading') -%>
<%= form_for Segment.new do |form| %>
  <fieldset>
    <legend><%= t('segments.new.form.legend') -%></legend>
    <%= render :partial => 'form', :locals => {:form => form} -%>
  </fieldset>
<% end -%>

<table>
  <thead>
    <tr>
      <th>Locale</th>
      <th>Key</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
 
  <tbody>
    <%= render :partial => 'segment_row', :collection => @segments, :as => :segment -%>
  </tbody
</table>

app/views/segments/show.html.erb
<%= content_tag :h1, t('segments.show.heading', {:language => @segment.locale , :key => @segment.key}) -%>

<%= content_tag :div, @segment.content %>

<%= link_to t('segments.back_link'), segments_url -%>
<%= link_to t('segments.edit_link'), edit_segment_url(@segment) -%>